### PR TITLE
fix(devops): change versions for deprecated issues

### PR DESCRIPTION
**Pull request by fagomezra**
fix(devops): change versions for deprecated issues

### CODE REVIEW

**Comment by JAMares** [comment]
After this PR, is necesary clean container and images ?

**Review by xavier506 — APPROVED** [review]
LGTM

**Comment by fagomezra** [comment]
> After this PR, is necesary clean container and images ?

No, this PR only fix the warnings in the github actions.

**Comment by JAMares** [comment]
Ok, thanks

**Pull request merged**
